#!/bin/bash

set -e

if [ -n "$(git status --porcelain)" ]; then
  echo "tree is dirty, please commit changes before building"
  exit 1
fi

script/lint

script/test

NODE_ENV=production $(npm bin)/webpack

$(npm bin)/node-sass ./dayz.scss > dist/dayz.css

if [ -n "$(git status --porcelain)" ]; then
   echo "Adding docs"
   git add docs/*
   git commit -m 'Update demo files for ghpages'
fi

echo "Done"
