#!/bin/bash

# script/test: Run test suite for application. Optionally pass in a path to an
#              individual test file to run a single test.


set -e

cd "$(dirname "$0")/.."

[ -z "$DEBUG" ] || set -x

echo "Tests started at…"
date "+%H:%M:%S"

$(npm bin)/jest
